In [ ]:
import cv2
import os
import numpy as np
import sklearn.metrics

In [ ]:

Images = []

imgDog = []
for files in os.walk('animals/dogs'):
    for d in files[2]:
        imgd = cv2.imread('animals/dogs/'+d)
        imgd = cv2.resize(imgd,dsize=(32,32))
        imgd = np.ravel(imgd)
        imgDog.append(imgd)
imgDog = np.array(imgDog)
yd = np.full((1000,1), 0) 
imglDog = np.append(imgDog,yd,axis=1)
Images.extend(imglDog)


imgCat = []
for files in os.walk('animals/cats'):
    for c in files[2]:
        imgc = cv2.imread('animals/cats/'+c)
        imgc = cv2.resize(imgc,dsize=(32,32))
        imgc = np.ravel(imgc)
        imgCat.append(imgc)
imgCat = np.array(imgCat)
yc = np.full((1000,1), 1)
imglCat = np.append(imgCat,yc,axis=1)
Images.extend(imglCat)


imgPanda = []
for files in os.walk('animals/panda'):
    for p in files[2]:
        imgp = cv2.imread('animals/panda/'+p)
        imgp = cv2.resize(imgp,dsize=(32,32))
        imgp = np.ravel(imgp)
        imgPanda.append(imgp)
imgPanda = np.array(imgPanda)
yp = np.full((1000,1), 2)
imglPanda = np.append(imgPanda,yp,axis=1)
Images.extend(imglPanda)
X = np.array(Images) 
print(X.shape)

(3000, 3073)


In [ ]:

np.random.shuffle(X)
train, validate, test = np.split(X, [int(.6 * len(X)), int(.7 * len(X))])

print('The size of Train set' ,train.shape)
print('The size of Test set' ,test.shape)
print('The size of Validation set' ,validate.shape)


trainX, trainY = (train[:, :-1], train[:, -1])
testX, testY = (test[:, :-1], test[:, -1])
valX, valY = (validate[:, :-1], validate[:, -1])

The size of Train set (1800, 3073)
The size of Test set (900, 3073)
The size of Validation set (300, 3073)


In [ ]:

distmatrix=[]
distList = []

for a in range(0,len(testX)):
    distList = []
    for b in range (0,len(trainX)):
        distList.append(sum(abs(trainX[b] - testX[a])))
    distmatrix.append(distList)

In [ ]:

k_list = [10,50,150,200,250,300,350,400,500];
Apreds = []
for k in k_list:
    preds=[]
    for j in range(0,len(distmatrix)):
        list12 = []
        for i in range(0,len(distmatrix[j])):
            list12.append((distmatrix[j][i],trainY[i]))
            list12 = sorted(list12, key=lambda a_entry: a_entry[0])[:k]
            for l in range(0,len(list12)):
                fin_list = []
                fin_list.append(list12[l][1])
        preds.append((max(set(fin_list), key=fin_list.count)))
    Apreds.append(preds)

In [ ]:

for d in range(0,len(Apreds)):
    z = np.asarray(Apreds[d])
    z = np.reshape(z,(900))
    print("\nThe Classification Report for k = " + str(k_list[d]) +"\n\n", sklearn.metrics.classification_report(testY, z)) 
    print("The Accuracy is = \n\n", sklearn.metrics.accuracy_score(testY, z))
    print("\nThe Confusion Matrix is = \n\n", sklearn.metrics.confusion_matrix(testY,z))



The Classification Report for k = 10

               precision    recall  f1-score   support

           0       0.35      0.45      0.39       277
           1       0.36      0.49      0.42       294
           2       0.73      0.33      0.45       329

   micro avg       0.42      0.42      0.42       900
   macro avg       0.48      0.42      0.42       900
weighted avg       0.49      0.42      0.42       900

The Accuracy is = 

 0.4177777777777778

The Confusion Matrix is = 

 [[125 132  20]
 [132 143  19]
 [102 119 108]]

The Classification Report for k = 50

               precision    recall  f1-score   support

           0       0.34      0.52      0.41       277
           1       0.35      0.41      0.38       294
           2       0.67      0.29      0.40       329

   micro avg       0.40      0.40      0.40       900
   macro avg       0.46      0.40      0.40       900
weighted avg       0.47      0.40      0.40       900

The Accuracy is = 

 0.3977777777777778

T

In [ ]:

distmatrix1=[]
distList1 = []

for a1 in range(0,len(valX)):
    distList1 = []
    for b1 in range (0,len(trainX)):
        distList1.append(sum(abs(trainX[b1] - valX[a1])))
    distmatrix1.append(distList1)

len(distmatrix1)

300

In [ ]:

k1 = 300
Apreds1 = []
preds1 = []
for j1 in range(0,len(distmatrix1)):
    list22 = []
    for i1 in range(0,len(distmatrix1[j1])):
        list22.append((distmatrix1[j1][i1],trainY[i1]))
        list22 = sorted(list22, key=lambda a_entry: a_entry[0])[:k1]
        for l1 in range(0,len(list22)):
            fin_list1 = []
            fin_list1.append(list22[l1][1])
    preds1.append((max(set(fin_list1), key=fin_list1.count)))
Apreds1.append(preds1)

In [ ]:
z1 = np.asarray(Apreds1)
z1 = np.reshape(z1,(300))
print("\nThe Classification Report for Validation Set with K = "+ str(k1) +" is\n\n ", sklearn.metrics.classification_report(valY, z1)) 
print("The Accuracy is = \n\n", sklearn.metrics.accuracy_score(valY, z1))
print("\nThe Confusion Matrix is = \n\n", sklearn.metrics.confusion_matrix(valY,z1))


The Classification Report for Validation Set with K = 300 is

                precision    recall  f1-score   support

           0       0.35      0.41      0.38       104
           1       0.33      0.35      0.34       101
           2       0.36      0.27      0.31        95

   micro avg       0.35      0.35      0.35       300
   macro avg       0.35      0.34      0.34       300
weighted avg       0.35      0.35      0.34       300

The Accuracy is = 

 0.3466666666666667

The Confusion Matrix is = 

 [[43 38 23]
 [43 35 23]
 [37 32 26]]
